spring.application.name=demo
spring.cloud.gateway.routes[0].id=example_route
spring.cloud.gateway.routes[0].uri=http://example.org
spring.cloud.gateway.routes[0].predicates[0]=Path=/example/**
spring.cloud.gateway.routes[1].id=load_balanced_route
spring.cloud.gateway.routes[1].uri=lb://example-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/loadbalanced/**
# Circuit Breaker Route
spring.cloud.gateway.routes[2].id=resilience_route
spring.cloud.gateway.routes[2].uri=http://this-service-does-not-exist.org
spring.cloud.gateway.routes[2].predicates[0]=Path=/resilience/**
spring.cloud.gateway.routes[2].filters[0]=CircuitBreaker=exampleCircuitBreaker

# Resilience4j Rules
resilience4j.circuitbreaker.instances.exampleCircuitBreaker.slidingWindowSize=10
resilience4j.circuitbreaker.instances.exampleCircuitBreaker.failureRateThreshold=50